# Example configuration for Balancer with BalancerQueries contract
endpoint = "https://api.balancer.fi"
rpc-url = "http://localhost:8545"

# Optional: Override default contract addresses
# vault = "0xBA12222222228d8Ba445958a75a0704d566BF2C8"
# v3_batch_router = "0x5AE4820889Fca51F0D2B6f6cC511f4b74E11b0E0"
# queries = "0xE39B5e3B6D74016b2F6A9673D7d7493B6DF549d5"  # Example address
# permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Chain ID for automatic contract address resolution
chain_id = 1 # Ethereum mainnet

# Optional: Enable specific API versions (defaults to all if not specified)
# enabled_api_versions = ["V2", "V3"]
